CimpleChat/Controllers/ChannelController.cs
using CimpleChat.Models;
using CimpleChat.Models.Channel;
using CimpleChat.Services.ChannelService;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;

namespace CimpleChat.Controllers
{
    public class ChannelController : Controller
    {
        private readonly IGroupMessageService _channelService;
        private readonly HttpContext? _context;
        private readonly IDataProtector _protector;
        private readonly IConfiguration _configuration;

        public ChannelController(IGroupMessageService channelService, 
            IHttpContextAccessor context,
            IDataProtectionProvider dataProtectionProvider,
            IConfiguration configuration)
        {
            _channelService = channelService;
            _context = context.HttpContext;
            _protector = dataProtectionProvider.CreateProtector("TestString");
            _configuration = configuration;
        }

        public IActionResult Index(int channelId)
        {
            string protectedCookie = _context!.Request.Cookies["userInfo"] ?? string.Empty;

            if (!string.IsNullOrEmpty(protectedCookie))
            {
                string cookieValue = _protector.Unprotect(protectedCookie);
                var user = System.Text.Json.JsonSerializer.Deserialize<User>(cookieValue);
                
                if(user != null)
                {
                    ViewBag.Username = user.Name;
                    ViewBag.UserId = user.Id;
                    ViewBag.UserProfileCharacter = user.Name.Substring(0, 1).ToUpper();

                    // add user to the channel
                    _channelService.AddUserToChannel(channelId, user.Id);
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.ChannelId = channelId;

            return View();
        }

        public IActionResult Create(string channelName, int type)
        {
            string protectedCookie = _context!.Request.Cookies["userInfo"] ?? string.Empty;
            
            if (!string.IsNullOrEmpty(protectedCookie))
            {
                string cookieValue = _protector.Unprotect(protectedCookie);
                var user = System.Text.Json.JsonSerializer.Deserialize<User>(cookieValue);

                if (user != null)
                {
                    string validateMsg = ValidateChannelName(channelName);

                    if (string.IsNullOrEmpty(validateMsg) && (type == 0 || type == 1))
                    {
                        long channelId = _channelService.AddNewChannel(channelName, (type == 0) ? ChannelType.@private : ChannelType.@public);

                        _channelService.AddUserToChannel(channelId, user.Id);

                        return Json(new { ChannelId = channelId });
                    }
                    else
                    {
                        return Json(new { Error = validateMsg });
                    }                  
                }
            }

            return Json(new { Error = "Invalid user info." });
        }

        public void AddMemberToChannel(long channelId, long userId)
        {
            string protectedCookie = _context!.Request.Cookies["userInfo"] ?? string.Empty;

            if (!string.IsNullOrEmpty(protectedCookie))
            {
                string cookieValue = _protector.Unprotect(protectedCookie);
                var user = System.Text.Json.JsonSerializer.Deserialize<User>(cookieValue);

                if (user != null)
                {
                    if(userId == user.Id)
                    {
                        _channelService.AddMemberToPublicChannel(channelId, user.Id);
                    }
                    else
                    {
                        _channelService.AddMemberToPrivateChannel(channelId, userId, user.Id);
                    }
                }
            }
        }

        public IActionResult SearchChannels(string search)
        {            
            var channelList = _channelService.SearchChannel(search.Trim());

            return Json(channelList);
        }

        private string ValidateChannelName(string channelName)
        {
            Regex regex = new Regex(@"^[a-zA-Z][a-zA-Z0-9]{2,17}$");

            if (!string.IsNullOrEmpty(channelName) && !regex.IsMatch(channelName))
            {
                return "Invalid channel name.";
            }
            else if (channelName.Length <=2 )
            {
                return "Invalid channel name.";
            }
            else if(!IsChannelNameAvailable(channelName))
            {
                return "Channel name is already available.";
            }

            return "";
        }

        private bool IsChannelNameAvailable(string name)
        {
            // determine that is channel name is available to register.
            // return false if a channel is already exist under same name.

            if (_channelService.IsChannelNameExist(name))
            {
                return false;
            }
            return true;
        }
    }
}

CimpleChat/Controllers/HomeController.cs
using CimpleChat.Models;
using CimpleChat.Services.ChannelService;
using CimpleChat.Services.UserService;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;

namespace TPChat.Controllers
{
    public class HomeController : Controller
    {
        private readonly HttpContext _context;
        private readonly IDataProtector _protector;
        private readonly IConfiguration _configuration;
        private readonly IUserService _userService;
        private readonly IGroupMessageService _channelService;
        

        public HomeController(IHttpContextAccessor httpContextAccessor,
                              IDataProtectionProvider protectionProvider,
                              IConfiguration configuration,
                              IUserService userService,
                              IGroupMessageService groupMessageService) {
            
            _context = httpContextAccessor.HttpContext;
            _protector = protectionProvider.CreateProtector(configuration["CookiePurpose"].ToString());
            _configuration = configuration;
            _channelService = groupMessageService;
            _userService = userService;
        }
        
        public IActionResult Index()
        {
            string? protectedCookie = _context.Request.Cookies["userInfo"];

            if (!string.IsNullOrEmpty(protectedCookie))
            {
                string cookieValue = _protector.Unprotect(protectedCookie);
                var user = System.Text.Json.JsonSerializer.Deserialize<User>(cookieValue);

                ViewBag.Username = user.Name;
                ViewBag.UserId = user.Id;
                ViewBag.UserProfileCharacter = user.Name.Substring(0, 1).ToUpper();
            }

            return View();
        }

        public IActionResult SearchUser(string name)
        {
            string? protectedCookie = _context.Request.Cookies["userInfo"];

            if (!string.IsNullOrEmpty(protectedCookie))
            {
                string cookieValue = _protector.Unprotect(protectedCookie);
                var user = System.Text.Json.JsonSerializer.Deserialize<User>(cookieValue);

                if(user != null && !string.IsNullOrEmpty(name) && name.Length > 2)
                {
                    var userList = _userService.SearchUser(name);
                    return Json(userList);
                }
            }

            return Json(new { Error = "Invalid request"});
        }

        public void UpdateActiveStatus()
        {
            string? protectedCookie = _context.Request.Cookies["userInfo"];

            if (!string.IsNullOrEmpty(protectedCookie))
            {
                string cookieValue = _protector.Unprotect(protectedCookie);
                var user = System.Text.Json.JsonSerializer.Deserialize<User>(cookieValue);

                if (user != null)
                {
                    _userService.UpdateLastActiveOn(user.Id);
                }
            }
        }
    }
}

CimpleChat/Controllers/RegistrationController.cs
using CimpleChat.Models;
using CimpleChat.Services.UserService;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;

namespace CimpleChat.Controllers
{
    public class RegistrationController : Controller
    {
        #region Properties

        private readonly IDataProtector _protector;
        private readonly IUserService _userService;
        private readonly IConfiguration _configuration;

        #endregion

        #region Ctor

        public RegistrationController(
            IConfiguration configuration,
            IDataProtectionProvider protectionProvider, 
            IUserService userService)
        {
            _protector = protectionProvider.CreateProtector(configuration["CookiePurpose"]);
            _userService = userService;
            _configuration = configuration;
        }

        #endregion

        #region Public Methods

        [HttpPost]
        public IActionResult Index([FromBody] RegisterUser userInfo)
        {
            string validationResponse = ValidateUser(userInfo);

            if (!string.IsNullOrEmpty(validationResponse))
            {
                var resp = new
                {
                    status = "error",
                    message = validationResponse,
                };

                return Json(resp);
            }

            if (_userService.IsUsernameAvailable(userInfo.UserName))
            {
                var user = _userService.AddNewUser(userInfo.UserName);

                string cookeiInfo = System.Text.Json.JsonSerializer.Serialize(user);

                var resp = new
                {
                    status = "success",
                    message = $"Username \"{userInfo.UserName}\" is available.",
                    userId = user.Id,
                    username = user.Name,
                    cookieInfo = _protector.Protect(cookeiInfo),
                };
                return Json(resp);
            }

            var response = new
            {
                status = "error",
                message = $"Username \"{userInfo.UserName}\" is not available."
            };

            return Json(response);
        }  

        public IActionResult IsUserNameAvailable(string username)
        {
            Regex regex = new Regex(@"^[a-zA-Z][a-zA-Z0-9]{2,17}$");
            string status = string.Empty;
            string message = string.Empty;

            if (string.IsNullOrEmpty(username) || !regex.IsMatch(username))
            {
                status = "error";
                message = $"Username \"{username}\" is invalid.";
            }
            else
            {
                if (!_userService.IsUsernameAvailable(username))
                {
                    status = "error";
                    message = $"Username \"{username}\" is not available.";
                }
                else
                {
                    status = "success";
                    message = $"Username \"{username}\" is available.";
                }
            }
            
            var response = new
            {
                status = status,
                message = message,
            };

            return Json(response);
        }

        #endregion

        #region Private Methods

        private string ValidateUser(RegisterUser userInfo)
        {
            Regex regex = new Regex(@"^[a-zA-Z][a-zA-Z0-9]{2,17}$");

            if (userInfo == null)
            {
                return "User info is invalid.";
            }            
            else if (!string.IsNullOrEmpty(userInfo.UserName) && !regex.IsMatch(userInfo.UserName))
            {
                return "Invalid username.";
            }
            else if (userInfo.Age < 16 || userInfo.Age > 100)
            {
                return "Invalid age.";
            }

            return "";
        }

        #endregion
    }
}

CimpleChat/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="modal fade" id="registrationModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="registrationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="registrationModalLabel">Anonymous Login</h5>
            </div>
            <div class="modal-body">
                <form id="userRegistrationForm">
                    
                    <div class="row">
                        <div class="col">
                            <div class="row">
                                <label for="inputUsername" class="col-sm-2 col-form-label"><i class="fa-solid fa-user"></i></label>
                                <div class="col-sm-10">
                                    <input type="text" id="inputUsername" class="form-control form-control-sm" aria-describedby="usernameValidationMessage" placeholder="Username" required>
                                </div>
                            </div>                           
                        </div>
                        <div class="col">
                            <span id="usernameValidationMessage" class="form-text text-danger"></span>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col">

                            <div class="row">      
                                <span class="col-sm-2 col-form-label"><i class="fa-solid fa-venus-mars"></i></span>
                                <div class="col-sm-10 pt-1">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inputGender" id="inputGenderMale" value="male" checked>
                                        <label class="form-check-label" for="inputGenderMale">Male</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inputGender" id="inputGenderFemale" value="female">
                                        <label class="form-check-label" for="inputGenderFemale">Female</label>
                                    </div>
                                </div>
                            </div>
                            <!--
                            <div class="row">
                                <label for="inputCountry" class="col-sm-2 col-form-label"><i class="fa-solid fa-globe"></i></label>
                                <div class="col-sm-10">
                                    <select class="form-select form-select-sm" id="inputCountry">
                                        <option selected>Bangladesh</option>
                                        <option value="1">United State of America</option>
                                    </select>
                                </div>
                            </div> 
                            -->
                        </div>
                        <div class="col">
                            <div class="row">
                                <label for="inputAge" class="col-sm-2 col-form-label"><i class="fa-solid fa-calendar-days"></i></label>
                                <div class="col-sm-10">
                                    <input type="number" id="inputAge" class="form-control form-control-sm" placeholder="Age" required>
                                </div>
                            </div>
                            <!--
                            <div class="row">
                                <label for="inputRegion" class="col-sm-2 col-form-label"><i class="fa-solid fa-location-dot"></i></label>
                                <div class="col-sm-10">
                                    <select class="form-select form-select-sm" id="inputRegion">
                                        <option selected></option>
                                        <option value="1"></option>
                                        <option value="2"></option>
                                    </select>
                                </div>
                            </div>
                            -->
                           
                        </div>
                    </div>
                    <!--
                    <div class="row">
                        <div class="col">
                            I am not a robot
                        </div>
                    </div>
                    -->
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" id="registerUserBtn" class="btn btn-primary">Login</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="createChannelModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create Channel</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-8">
                        <input type="text" class="form-control" id="channelNameInput" placeholder="Channel name">
                        <span id="channelNameErrorMsg" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input type="text" id="channelTypeInput" class="form-control" value="Private" disabled>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="createChannelBtn">Create</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addMemberModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="col">
                    <input type="text" class="form-control" id="addMemberSearchInput"/>
                    <div class="" style="max-height: 300px; overflow: auto;" id="addMemberSearchResultContainer"></div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row mt-3">
    <div class="col d-flex flex-row border" id="wrapper">
        <div class="left-panel">
            <div class="channel-container d-flex flex-column private-channel-container">
                <div class="channel-header d-flex flex-row align-items-center">
                    <h5 class="flex-fill">Private</h5>
                    <i class="fa-solid fa-plus" id="createPrivateChannel"></i>
                    <i class="fa-solid fa-angle-down dropdown-arrow-private"></i>
                    <!--
                    <i class="fa-solid fa-angle-up"></i>
                    
                    <i class="fa-solid fa-magnifying-glass ml-3"></i>
                    -->
                </div>
                <div class="channel-list" id="privateChannelListContainer">
                    <!--
                    <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            A list item
                            <span class="badge bg-primary rounded-pill">14</span>
                        </li>                       
                    </ul>
                    -->
                </div>
            </div>

            <div class="channel-container d-flex flex-column public-channel-container">
                <div class="channel-header d-flex flex-row align-items-center">
                    <h5 class="flex-fill">Public</h5>
                    <i class="fa-solid fa-plus" id="createPublicChannel"></i>
                    <i class="fa-solid fa-angle-down dropdown-arrow-public"></i>
                    <!--
                    <i class="fa-solid fa-angle-up"></i>
                    <i class="fa-solid fa-magnifying-glass ml-3"></i>
                    -->
                </div>
                <div class="channel-list" id="publicChannelListContainer">
                    <!--
                    <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            A list item
                            <span class="badge bg-primary rounded-pill">14</span>
                        </li>
                    </ul>
                    -->                 
                </div>
            </div>
            
        </div>
        <div class="flex-fill d-flex flex-column border bg-white p-2">
            <div class="flex-fill d-flex flex-column" id="msgWindow">
                <div class="d-flex flex-row msg-header pb-2">
                    <h5 class="flex-fill m-0"></h5>
                    <!--
                    <span>Member: 120</span>
                    -->
                    <button class="btn btn-sm" id="addMemberBtn" style="display: none;"><i class="fa-solid fa-plus"></i> Add Member</button>
                </div>
                <div class="flex-fill msg-body" style="background: #EEE;">
                    <div style="position: relative; width: 100%; height: 100%; overflow: hidden;">
                        <div class="" style="position:absolute; bottom: 5px; width: 100%; overflow-y: scroll; scrollbar-width: thin; max-height:100%;" id="msgContainer">
                        </div>
                    </div>
                </div>
            </div>
            <div id="footerWrapper" class="d-flex flex-column pt-2">
                <div class="d-flex flex-row align-items-start">
                    <div class="flex-fill">
                        <!--
                        <div class="w-100 border rounded" id="msgInputField" style="max-height: 66px; overflow-y: auto; padding: 0px 5px 5px 5px; min-height: 32px;">
                            <p class="m-0"><span id="inputCursor">|</span></p>
                        </div>
                        -->
                        <input type="text" class="form-control" id="msgContent" />

                    </div>
                    <button class="btn btn-primary btn-sm round ms-2" id="btnSendMsg"><i class="fa-solid fa-paper-plane"></i></button>
                </div>
                <div class="d-flex flex-row justify-content-start">
                    <button class="btn btn-sm"><i class="fa-solid fa-image"></i></button>
                    <button class="btn btn-sm"><i class="fa-solid fa-paperclip"></i></button>
                    <button class="btn btn-sm"><i class="fa-solid fa-microphone-lines"></i></button>
                    <!--
                    <button class="btn btn-sm"><i class="fa-solid fa-link"></i></button>
                    <button class="btn btn-sm"><i class="fa-solid fa-face-smile"></i></button>
                    -->                 
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
<script>
    const Urls = {
        registration: '@Url.Action("Index", "Registration")',
        validateUniqueUsername: '@Url.Action("IsUserNameAvailable", "Registration")',
        channel: '@Url.Action("Index", "Channel")',
        channelList: '@Url.Action("GetChannelList", "Channel")',
        updateUserStatus: '@Url.Action("UpdateActiveStatus", "Home")',
        searchChannel: '@Url.Action("SearchChannels", "Channel")',
        searchUser: '@Url.Action("SearchUser", "Home")',
        addMemberToChannel: '@Url.Action("AddMemberToChannel", "Channel")',
        createChannel: '@Url.Action("Create", "Channel")',
    };

    $(document).ready(function () {
        var UI = CimpleChat.UI;

        UI.adjustMainContainerHeight();
        UI.initEvents();
        CimpleChat.UserRegistration.initRegistration('#registrationModal');
        CimpleChat.Common.setConst('userId', '@ViewBag.userId');
        CimpleChat.Common.setConst('username', '@ViewBag.Username');

        $('#btnSendMsg').on('click', function () {
            CimpleChat.Channel.sendMessage($('#msgContent').val(), function () {
                $('#msgContent').val('');
            });
        });

        $('#msgContent').on('keydown', function (event) {
            if (event.key === "Enter") {
                $('#btnSendMsg').trigger('click');
            }
        });

        $('#msgContent').focus(function () {
            console.log("focus");
            CimpleChat.Chat.UIRender.updateSeenFlag();
        });

        $('#msgContainer').scroll(function () {
            console.log("scroll");
            CimpleChat.Chat.UIRender.updateSeenFlag();
        });




        // $(document).on('click', '.channel-name', function () {
        //     let channelId = $(this).attr('data-channel');
        //     window.location = Urls.channel + '/?channelId=' + channelId;
        // });

        

        // CimpleChat.Common.updateUserStatus(Urls.updateUserStatus);
        
        // setInterval(
        //     function () {
        //         CimpleChat.Channel.getChannelList(CimpleChat.Channel.renderChannels)
        //     },
        //     15000
        // );    
    });
</script>
}
        